const BUILDINGS = [
    {"code": "001", "name": "BARNES HALL"}, {"code": "002", "name": "BENBOW HALL"}, {"code": "003", "name": "Fort IRC RESEARCH CENTER"},
    {"code": "004", "name": "CAMPBELL HALL - ROTC"}, {"code": "005", "name": "CARVER HALL"}, {"code": "006", "name": "Monroe HALL"},
    {"code": "007", "name": "BLUFORD LIBRARY"}, {"code": "008", "name": "FRAZIER HALL"}, {"code": "010", "name": "GRAHAM HALL"},
    {"code": "012", "name": "HINES HALL & ANNEX"}, {"code": "013", "name": "HODGIN HALL"}, {"code": "014", "name": "Holt Hall"},
    {"code": "015", "name": "MOORE GYMNASIUM"}, {"code": "016", "name": "HOUSE KP EQ REPAIRS"}, {"code": "017", "name": "SMITH HALL"},
    {"code": "018", "name": "PRICE HALL"}, {"code": "019", "name": "Price Annex"}, {"code": "020", "name": "REID GREENHOUSE"},
    {"code": "021", "name": "SOCKWELL HALL"}, {"code": "022", "name": "WARD HALL"}, {"code": "023", "name": "CROSBY HALL"},
    {"code": "024", "name": "MERRICK HALL"}, {"code": "025", "name": "ALEX HALEY DORM (Haley Hall)"}, {"code": "026", "name": "ZOE BARBEE HALL"},
    {"code": "027", "name": "Gamble Complex"}, {"code": "028", "name": "PORTABLE BUILDING"}, {"code": "033", "name": "NEW GREENHOUSE - SOA"},
    {"code": "035", "name": "CHILD DEVELOP LAB"}, {"code": "040", "name": "1020 WENDOVER"}, {"code": "041", "name": "BIO GREENHOUSE"},
    {"code": "042", "name": "BIO-DIESEL UNIT"}, {"code": "044", "name": "GEN. CLASSRM & LAB (GCB-A)"}, {"code": "045", "name": "CRAIG HALL (GCB-B)"},
    {"code": "048", "name": "Union Square NCA&T & UNCG Nursing Bldg"}, {"code": "050", "name": "Nussbaum Center"}, {"code": "052", "name": "890 E. Lindsay St."},
    {"code": "054", "name": "Aggie Suites E"}, {"code": "056", "name": "Aggie Suites F"}, {"code": "058", "name": "Pride Hall"},
    {"code": "060", "name": "HAZARDOUS MATER. STG"}, {"code": "062", "name": "NEW SCIENCE BLDG"}, {"code": "072", "name": "Aggie Softball Field Assign # 1"},
    {"code": "076", "name": "PROCTOR HALL"}, {"code": "078", "name": "FYRE (NACB GEN ACADEM. CLASSRM)"}, {"code": "108", "name": "COOPER HALL"},
    {"code": "110", "name": "CURTIS HALL"}, {"code": "111", "name": "DUDLEY MEM. BLDG"}, {"code": "112", "name": "STRICKLAND FLD HOUSE"},
    {"code": "113", "name": "GARRETT HOUSE"}, {"code": "114", "name": "ALMA MORROW HALL"}, {"code": "116", "name": "HARRISON AUDITORIUM"},
    {"code": "119", "name": "HOLLAND HALL"}, {"code": "121", "name": "MORRISON HALL"}, {"code": "122", "name": "NOBLE HALL"},
    {"code": "128", "name": "SEBASTIAN INFIRMARY"}, {"code": "129", "name": "AGGIE VILLAGE #3 - McCain"}, {"code": "130", "name": "AGGIE VILLAGE #6 - McNeil"},
    {"code": "131", "name": "AGGIE VILLAGE #1 - Richmond"}, {"code": "132", "name": "AGGIE VILLAGE #2 - Admin Offices"}, {"code": "133", "name": "NEW VANSTORY HALL"},
    {"code": "134", "name": "AGGIE VILLAGE #4 - Blair"}, {"code": "135", "name": "AGGIE VILLAGE #5 - Front Office"}, {"code": "137", "name": "Student Union"},
    {"code": "138", "name": "DEHUGLEY ANNEX"}, {"code": "139", "name": "DEHUGULEY PHYS PLANT"}, {"code": "140", "name": "Bryan FITNESS/WELLNESS CTR"},
    {"code": "145", "name": "BEHAV HLTH/WELL CTR"}, {"code": "150", "name": "STUDENT HEALTH CTR"}, {"code": "164", "name": "1640 Sullivan St"},
    {"code": "165", "name": "YMCA BUILDING"}, {"code": "167", "name": "311 STEWART STREET"}, {"code": "180", "name": "BAND FACILITY"},
    {"code": "201", "name": "BROWN HALL"}, {"code": "202", "name": "MAIN GARAGE"}, {"code": "203", "name": "NEAL HEATING PLANT"},
    {"code": "205", "name": "MURPHY HALL"}, {"code": "206", "name": "SWITCH BUILDING"}, {"code": "208", "name": "ERIC/Martin"},
    {"code": "209", "name": "WILLIAMS CAFETERIA"}, {"code": "300", "name": "CAMPUS REC CENTER"}, {"code": "402", "name": "THE OAKS"},
    {"code": "403", "name": "Faculty / Staff Senate House"}, {"code": "404", "name": "POULTRY PLANT"}, {"code": "405", "name": "Dairy Residence"},
    {"code": "408", "name": "CHANCELLOR'S RES"}, {"code": "409", "name": "Oaks Motel"}, {"code": "410", "name": "Ramada Inn"},
    {"code": "413", "name": "POULTRY REC UNIT A"}, {"code": "414", "name": "POULTRY RES UNIT B"}, {"code": "415", "name": "NEW DIARY BARN"},
    {"code": "416", "name": "Hazel Lane"}, {"code": "500", "name": "OBERMYER ST PK DK"}, {"code": "600", "name": "POULTRY/LOUN. BARN"},
    {"code": "601", "name": "Laying House #3"}, {"code": "602", "name": "OIL BUILDING"}, {"code": "603", "name": "NEW HAY BARN"},
    {"code": "604", "name": "Boiler House"}, {"code": "605", "name": "Turkey House"}, {"code": "606", "name": "Laying House #1"},
    {"code": "607", "name": "Laying House #2"}, {"code": "608", "name": "Manure House"}, {"code": "609", "name": "Lounging Barn"},
    {"code": "610", "name": "Milking Barn"}, {"code": "611", "name": "BULL BARN"}, {"code": "612", "name": "NEW LOUNGING BARN"},
    {"code": "613", "name": "Maternity Barn"}, {"code": "614", "name": "Abattoir"}, {"code": "615", "name": "TRACTOR SHED/CMPX 2"},
    {"code": "616", "name": "Beef Barn"}, {"code": "617", "name": "Farrowing Old"}, {"code": "619", "name": "FARM SHOP CMPLX #1"},
    {"code": "621", "name": "GRAIN STORAGE (SILO)"}, {"code": "622", "name": "NEW MUSHROOM RES."}, {"code": "623", "name": "AQUACULTURE RES."},
    {"code": "624", "name": "EXT & APP RESEARCH"}, {"code": "626", "name": "Graham Hall Annex"}, {"code": "627", "name": "Bryan House"},
    {"code": "629", "name": "PLANT AND SOIL LAB"}, {"code": "630", "name": "Police Administration"}, {"code": "631", "name": "CORBETT SPORT CTR"},
    {"code": "632", "name": "Gibbs"}, {"code": "633", "name": "MARTEENA HALL"}, {"code": "636", "name": "STADIUM"},
    {"code": "637", "name": "AG ECON. RES. FAC"}, {"code": "638", "name": "FARM MGR Residence"}
];