const BUILDINGS = [
    { "code": "51L", "name": "1010 E. Lindsay St." },
    { "code": "040", "name": "1020 WENDOVER" },
    { "code": "164", "name": "1640 Sullivan St" },
    { "code": "167", "name": "311 STEWART STREET" },
    { "code": "52L", "name": "890 E. Lindsay St." },
    { "code": "614", "name": "Abattoir" },
    { "code": "637", "name": "AG ECON. RES. FAC" },
    { "code": "651", "name": "AGGIE SHELT COOKOUT" },
    { "code": "072", "name": "Aggie Softball Field Assign # 1" },
    { "code": "054", "name": "Aggie Suites E" },
    { "code": "056", "name": "Aggie Suites F" },
    { "code": "131", "name": "AGGIE VILLAGE # 1 - Richmond" },
    { "code": "132", "name": "AGGIE VILLAGE # 2 - Admin Offices" },
    { "code": "129", "name": "AGGIE VILLAGE # 3 - McCain" },
    { "code": "134", "name": "AGGIE VILLAGE # 4 - Blair" },
    { "code": "135", "name": "AGGIE VILLAGE # 5 - Front Office" },
    { "code": "130", "name": "AGGIE VILLAGE # 6 - McNeil" },
    { "code": "025", "name": "ALEX HALEY DORM (Haley Hall)" },
    { "code": "114", "name": "ALMA MORROW HALL" },
    { "code": "623", "name": "AQUACULTURE RES." },
    { "code": "180", "name": "BAND FACILITY" },
    { "code": "001", "name": "BARNES HALL" },
    { "code": "616", "name": "Beef Barn" },
    { "code": "686", "name": "BEEF UNIT (Bull Barn)" },
    { "code": "145", "name": "BEHAV HLTH/WELL CTR" },
    { "code": "002", "name": "BENBOW HALL" },
    { "code": "041", "name": "BIO GREENHOUSE" },
    { "code": "041", "name": "BIO-DIESEL UNIT" },
    { "code": "007", "name": "BLUFORD LIBRARY" },
    { "code": "604", "name": "Boiler House" },
    { "code": "201", "name": "BROWN HALL" },
    { "code": "140", "name": "Bryan FITNESS/WELLNESS CTR" },
    { "code": "627", "name": "Bryan House" },
    { "code": "611", "name": "BULL BARN" },
    { "code": "660", "name": "BULL BARN" },
    { "code": "687", "name": "CALF BARN" },
    { "code": "004", "name": "CAMPBELL HALL - ROTC" },
    { "code": "300", "name": "CAMPUS REC CENTER" },
    { "code": "005", "name": "CARVER HALL" },
    { "code": "408", "name": "CHANCELLOR'S RES" },
    { "code": "642", "name": "CHARLES H. MOORE BLD" },
    { "code": "035", "name": "CHILD DEVELOP LAB" },
    { "code": "108", "name": "COOPER HALL" },
    { "code": "661", "name": "COOPERATIVE EXTENSN (Burlington Road) Ag Ext Farm Storage)" },
    { "code": "631", "name": "CORBETT SPORT CTR" },
    { "code": "045", "name": "CRAIG HALL (GCB-B)" },
    { "code": "023", "name": "CROSBY HALL" },
    { "code": "110", "name": "CURTIS HALL" },
    { "code": "405", "name": "Dairy Residence" },
    { "code": "138", "name": "DEHUGLEY ANNEX" },
    { "code": "139", "name": "DEHUGULEY PHYS PLANT" },
    { "code": "634", "name": "DOWDY ADMIN BLDG" },
    { "code": "111", "name": "DUDLEY MEM. BLDG" },
    { "code": "658", "name": "EQUINE UNIT" },
    { "code": "208", "name": "ERIC/Martin" },
    { "code": "624", "name": "EXT & APP RESEARCH" },
    { "code": "403", "name": "Faculty / Staff Senate House formerly - GEARUP/STUDNT PAPER" },
    { "code": "638", "name": "FARM MGR Residence" },
    { "code": "639", "name": "Farm Office Building" },
    { "code": "619", "name": "FARM SHOP CMPLX #1" },
    { "code": "617", "name": "Farrowing Old" },
    { "code": "690", "name": "FEEDER BEHD LR SILO" },
    { "code": "003", "name": "Fort IRC RESEARCH CENTER" },
    { "code": "008", "name": "FRAZIER HALL" },
    { "code": "078", "name": "FYRE (NACB GEN ACADEM. CLASSRM)" },
    { "code": "027", "name": "Gamble Complex" },
    { "code": "113", "name": "GARRETT HOUSE" },
    { "code": "044", "name": "GEN. CLASSRM & LAB (GCB-A)" },
    { "code": "632", "name": "Gibbs" },
    { "code": "010", "name": "GRAHAM HALL" },
    { "code": "626", "name": "Graham Hall Annex" },
    { "code": "621", "name": "GRAIN STORAGE (SILO)" },
    { "code": "116", "name": "HARRISON AUDITORIUM" },
    { "code": "685", "name": "HAY BARN #1" },
    { "code": "689", "name": "HAY BARN # 2" },
    { "code": "060", "name": "HAZARDOUS MATER. STG" },
    { "code": "416", "name": "Hazel Lane" },
    { "code": "012", "name": "HINES HALL & ANNEX" },
    { "code": "013", "name": "HODGIN HALL" },
    { "code": "119", "name": "HOLLAND HALL" },
    { "code": "014", "name": "Holt Hall" },
    { "code": "016", "name": "HOUSE KP EQ REPAIRS" },
    { "code": "645", "name": "HPR Greenhouse # 1" },
    { "code": "646", "name": "HPR Greenhouse # 2" },
    { "code": "647", "name": "HPR Greenhouse # 3" },
    { "code": "648", "name": "HPR Greenhouse # 4" },
    { "code": "649", "name": "HPR Greenhouse # 5" },
    { "code": "650", "name": "HPR Greenhouse # 6" },
    { "code": "652", "name": "HPR Greenhouse # 7" },
    { "code": "901", "name": "JOINT SCHOOL OF NANO" },
    { "code": "606", "name": "Laying House # 1" },
    { "code": "607", "name": "Laying House # 2" },
    { "code": "601", "name": "Laying House # 3" },
    { "code": "609", "name": "Lounging Barn" },
    { "code": "202", "name": "MAIN GARAGE" },
    { "code": "608", "name": "Manure House" },
    { "code": "633", "name": "MARTEENA HALL" },
    { "code": "613", "name": "Maternity Barn" },
    { "code": "644", "name": "MCNAIR ENGINEERING" },
    { "code": "024", "name": "MERRICK HALL" },
    { "code": "691", "name": "METAL PUMPHOUSE" },
    { "code": "610", "name": "Milking Barn" },
    { "code": "006", "name": "Monroe HALL" },
    { "code": "015", "name": "MOORE GYMNASIUM" },
    { "code": "121", "name": "MORRISON HALL" },
    { "code": "205", "name": "MURPHY HALL" },
    { "code": "641", "name": "MUSHRM BIO & RESRCH" },
    { "code": "203", "name": "NEAL HEATING PLANT" },
    { "code": "415", "name": "NEW DIARY BARN" },
    { "code": "659", "name": "NEW EQUIPMT SHELTER" },
    { "code": "033", "name": "NEW GREENHOUSE - SOA" },
    { "code": "603", "name": "NEW HAY BARN" },
    { "code": "612", "name": "NEW LOUNGING BARN" },
    { "code": "622", "name": "NEW MUSHROOM RES." },
    { "code": "062", "name": "NEW SCIENCE BLDG" },
    { "code": "133", "name": "NEW VANSTORY HALL" },
    { "code": "122", "name": "NOBLE HALL" },
    { "code": "50L", "name": "Nussbaum Center" },
    { "code": "409", "name": "Oaks Motel" },
    { "code": "500", "name": "OBERMYER ST PK DK" },
    { "code": "602", "name": "OIL BUILDING" },
    { "code": "665", "name": "OLD SHEEP BARN" },
    { "code": "667", "name": "OLD SWINE HOOP" },
    { "code": "629", "name": "PLANT AND SOIL LAB" },
    { "code": "630", "name": "Police Administration" },
    { "code": "028", "name": "PORTABLE BUILDING" },
    { "code": "404", "name": "POULTRY PLANT" },
    { "code": "413", "name": "POULTRY REC UNIT A" },
    { "code": "414", "name": "POULTRY RES UNIT B" },
    { "code": "600", "name": "POULTRY/LOUN. BARN" },
    { "code": "019", "name": "Price Annex" },
    { "code": "018", "name": "PRICE HALL" },
    { "code": "058", "name": "Pride Hall" },
    { "code": "076", "name": "PROCTOR HALL" },
    { "code": "682", "name": "PT-CAM" },
    { "code": "410", "name": "Ramada Inn" },
    { "code": "020", "name": "REID GREENHOUSE" },
    { "code": "128", "name": "SEBASTIAN INFIRMARY" },
    { "code": "684", "name": "SMALL RUMINANT RES (Sheep Barn)" },
    { "code": "017", "name": "SMITH HALL" },
    { "code": "021", "name": "SOCKWELL HALL" },
    { "code": "636", "name": "STADIUM" },
    { "code": "112", "name": "STRICKLAND FLD HOUSE" },
    { "code": "150", "name": "STUDENT HEALTH CTR" },
    { "code": "137", "name": "Student Union" },
    { "code": "694", "name": "SWINE RES FACUILITY" },
    { "code": "692", "name": "SWINE SHOP SHELT" },
    { "code": "640", "name": "SWINE UNIT" },
    { "code": "206", "name": "SWITCH BUILDING" },
    { "code": "402", "name": "THE OAKS" },
    { "code": "615", "name": "TRACTOR SHED/CMPX 2 (Machine Shed)" },
    { "code": "643", "name": "TRANSMISSION TOWER" },
    { "code": "605", "name": "Turkey House" },
    { "code": "048", "name": "Union Square NCA&T & UNCG Nursing Bldg" },
    { "code": "022", "name": "WARD HALL" },
    { "code": "019", "name": "WEBB ANIMAL SCI BLDG" },
    { "code": "209", "name": "WILLIAMS CAFETERIA" },
    { "code": "165", "name": "YMCA BUILDING" },
    { "code": "026", "name": "ZOE BARBEE HALL" }
];
